<MyGrid>

	nameFromClass: nameInHere
	emailFromClass: emailInHere
	
	GridLayout:
		cols: 1
		size: root.width - 200, root.height - 200
		pos: 100, 100
		
		GridLayout: 
			cols: 2
			
			Label:
				text: "Name: "
		
			TextInput:
				id: nameInHere
				multiline: False
			
			Label:
				text: "Email: "
		
			TextInput: 
				id: emailInHere
				multiline: False
			
		Button:
			text: "Submit"
			on_press: root.button()